### ISSUE TITLE
Reset cache

### ISSUE THREAD

**Issue by pedrokost** [fantactuka/jquery-ajax-goodies#7]
What would be the best approach to force a reload, bypassing the cache?

I could add an extra parameter ?ts=156343684 to the request, but the next time the request would be made without the parameter, the previously cached data would be returned.

Alternatively, I could add a $.deleteAjaxCache() to the plugin.

What is your opinion?

**Comment by pedrokost** [comment]
Bump, any ideas?

**Comment by fantactuka** [comment]
Hi there!

I can see two options here:
- pass `cached` option as a function that will return true / false depending on cache validity:

``` js
$.ajax({
  url: '...',
  cached: function(data, stamp) {
    return ...;
  }
})
```
- implement own adapter that has `removeAll` method to clean cache

``` js
var Adapter = {
  getItem: function() { },
  setItem: function() { },
  removeItem: function() { },
  removeAll: function() {
     ... clean all cached ...
  }
};

$.ajax.goodies.cached.setAdapter(Adapter);

// Later in code:
$.ajax({ ... });

// When need to clean cache for some reason
Adapter.removeAll();
```

**Comment by fantactuka** [comment]
Let me know if that works

**Comment by pedrokost** [comment]
@fantactuka Thank you for the help. I implemented the second solution you proposed and it is working very well.

In case anyone else needs this as well, I am leaving here a minimal adapter that implements this:

``` javascript
    var Adapter = {
        storage: {},

        setItem: function(key, value) {
            this.storage[key] = value;
        },

        getItem: function(key) {
            return this.storage[key];
        },

        removeItem: function(key) {
            delete this.storage[key];
        },

        removeAll: function() {
            this.storage = {};
        }
    };
```
